### ISSUE TITLE
Knowledge tool cannot ingest web pages with ".pdf" in the URL

### ISSUE THREAD

**Issue by sheng-liang** [otto8-ai/otto8#537]
When ingesting intel.com a bunch of pages errors out. They appears to be PDF files but are actually HTML pages. Pages like:

http://csrc.nist.gov/publications/nistpubs/800-38a/sp800-38a.pdf
http://csrc.nist.gov/publications/nistpubs/800-38B/SP_800-38B.pdf

![image](https://github.com/user-attachments/assets/df26bacf-773d-4e09-ab72-77e753ffc27a)

These PDF links actually direct you to a page like this:

![image](https://github.com/user-attachments/assets/052687d4-5c44-4119-b934-bd29c549159a)

**Comment by iwilltry42** [comment]
This should be fixed by now via https://github.com/otto8-ai/tools/pull/233

**Comment by sangee2004** [comment]
When testing with latest builds , we are syncing only 250 files . I am not seeing the exact files mentioned in the issue being synced probably because of hitting the 250 limit.


But there are lot of files which we skip syncing now when they are not actually a pdf file and a redirect:
 
```
time="2024-12-03T21:57:30Z" level=info msg="skipping https://intel.com/content/dam/www/central-libraries/us/en/documents/policy-human-rights.pdf because it is not a PDF (likely redirect on old link)"
```

Did not encounter this error when ingesting `intel.com`.

Also was able to verify this issue was not seen when testing related issue  https://github.com/otto8-ai/otto8/issues/150.
