### ISSUE TITLE
UI - No error message presented to user when deletion of model fails.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#707]
**Steps to reproduce the problem:**
1. Create an agent with any LLM model  like`gpt-3.5-turbo`
2. Try to delete this model.
3. Deletion of the model fails but there is no error message presented  to the user and model continues to be listed.

Delete API fails with `model "gpt-3.5-turbo" is used by 1 agents` and status `412 Precondition Failed`

**Expected behavior:**
In this case , user should be presented with the error message from the api.

**Comment by ivyjeong13** [comment]
@cjellick Since deletion of a model has been removed, I wanted to check if this issue can be closed? Though I was thinking of improving the existing setting active/inactive of a model (ex. adding a warning alert that models may break if they set to inactive & a snackbar alert when the active state is successfully changed)

**Comment by ivyjeong13** [comment]
Since deletion of a model has been removed, I believe this issue is no longer valid.

**Comment by sangee2004** [comment]
There is no way to delete models anymore.
